apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-demo
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: second-demo
        image: second-demo
---
apiVersion: v1
kind: Service
metadata:
  name: second-demo-service
  namespace: default
spec:
  type: NodePort
  selector:
    bb: web
  ports:
  - port: 8686
    targetPort: 8686
    nodePort: 30003