apiVersion: apps/v1
kind: Deployment
metadata:
  name: first
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: first-site
        image: first-4
---
apiVersion: v1
kind: Service
metadata:
  name: first-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    bb: web
  ports:
  - port: 8686
    targetPort: 8686
    nodePort: 30001