apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: first-deploy
  name: first-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: first-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: first-deploy
    spec:
      containers:
      - image: first-4
        name: first-4
        resources: {}
status: {}
